name: Maven Package

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get project version
        id: get_version
        run: echo "::set-output name=VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"

      - name: Upload JAR to WebDAV
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          curl -X MKCOL -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} https://repo.horvathdavidmiklos.hu/${VERSION}/
          curl -T authentication/target/authentication-${VERSION}.jar -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} https://repo.horvathdavidmiklos.hu/${VERSION}/authentication.jar
        env:
          WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}