name: Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Read version from file
        id: read_version
        run: echo "::set-output name=VERSION::$(cat VERSION)"

      - name: Build with Maven
        run: mvn -B package

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to WebDAV
        run: |
          VERSION=${{ steps.read_version.outputs.VERSION }}
          WEBDAV_URL="https://repo.horvathdavidmiklos.hu/${VERSION}/"

          # Create the directory
          curl -X MKCOL -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} "$WEBDAV_URL"

          # Find and upload JAR files
          for jar in $(find . -name "authentication-${VERSION}.jar"); do
            echo "Uploading $jar to $WEBDAV_URL"
            curl -T "$jar" -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} "$WEBDAV_URL$(basename $jar)"
          done
        env:
          WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
